name: CartelNameFix
main: com.cartel.namefix.Core
version: '${project.version}'
authors: [Cartel]
api-version: '1.18'
load: STARTUP
description: It prevents bugs and authorization errors made through authorized names.
commands:
  cartelnamefix:
    description: Basic command for Cartel Name Fix